import React, { Component } from 'react';

class ChallengeRatingTable extends Component {
  render() {
    return (
        <div className="dm-container">
            <div className="dm-container-name">Proficiency and EXP by Challenge Rating</div>
            <table className="dm-container-table width-100">
                <thead>
                    <tr>
                        <th>CR</th>
                        <th>EXP Value</th>
                        <th>Proficiency Bonus</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>200</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>450</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>700</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>1100</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>1800</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>2300</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>2900</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>3900</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>9</td>
                        <td>5000</td>
                        <td>4</td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>5900</td>
                        <td>4</td>
                    </tr>
                    <tr>
                        <td>11</td>
                        <td>7200</td>
                        <td>4</td>
                    </tr>
                    <tr>
                        <td>12</td>
                        <td>8400</td>
                        <td>4</td>
                    </tr>
                    <tr>
                        <td>13</td>
                        <td>10000</td>
                        <td>5</td>
                    </tr>
                    <tr>
                        <td>14</td>
                        <td>11500</td>
                        <td>5</td>
                    </tr>
                    <tr>
                        <td>15</td>
                        <td>13000</td>
                        <td>5</td>
                    </tr>
                    <tr>
                        <td>16</td>
                        <td>15000</td>
                        <td>5</td>
                    </tr>
                    <tr>
                        <td>17</td>
                        <td>18000</td>
                        <td>6</td>
                    </tr>
                    <tr>
                        <td>18</td>
                        <td>20000</td>
                        <td>6</td>
                    </tr>
                    <tr>
                        <td>19</td>
                        <td>22000</td>
                        <td>6</td>
                    </tr>
                    <tr>
                        <td>20</td>
                        <td>25000</td>
                        <td>6</td>
                    </tr>
                    <tr>
                        <td>21</td>
                        <td>33000</td>
                        <td>7</td>
                    </tr>
                    <tr>
                        <td>22</td>
                        <td>41000</td>
                        <td>7</td>
                    </tr>
                    <tr>
                        <td>23</td>
                        <td>50000</td>
                        <td>7</td>
                    </tr>
                    <tr>
                        <td>24</td>
                        <td>62000</td>
                        <td>7</td>
                    </tr>
                    <tr>
                        <td>25</td>
                        <td>75000</td>
                        <td>8</td>
                    </tr>
                    <tr>
                        <td>26</td>
                        <td>90000</td>
                        <td>8</td>
                    </tr>
                    <tr>
                        <td>27</td>
                        <td>105000</td>
                        <td>8</td>
                    </tr>
                    <tr>
                        <td>28</td>
                        <td>120000</td>
                        <td>8</td>
                    </tr>
                    <tr>
                        <td>29</td>
                        <td>135000</td>
                        <td>9</td>
                    </tr>
                    <tr>
                        <td>30</td>
                        <td>155000</td>
                        <td>9</td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
  }
}

export default ChallengeRatingTable;
